version: 0.2

phases:
  build:
    commands:
      - npm install yarn
      - yarn install --frozen-lockfile
      - yarn run build
      - if [ "$TOPDIR" == "prod" ]; then CFID=$PRODID; fi
      - aws s3 sync build $DEPLOY_BUCKET/$TOPDIR
      - aws cloudfront create-invalidation --distribution-id $CFID --paths '/*'
