name: Deploy Vapor Quality Image to ECR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag for Vapor-Quality ECR."
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    name: Build and push to Amazon ECR
    runs-on: ubuntu-latest

    steps:
      - name: Github Workflow Information
        run: |
          echo "Image Tag: ${{github.event.inputs.tag}}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::624855356446:role/GHA
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
    
      - name: Build, tag, and push image to Amazon ECR
        id: set-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: vapor-quality
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
