name: Build App and Deploy

on:
  push:
    branches: [ gh-pages-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application and push
        run: |
          yarn install
          yarn deploy